// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXDT12am_VMfR5u0JhRXT4-R9_xHBTCf4',
    appId: '1:420909429462:web:8b8fb1533e26939ff24f77',
    messagingSenderId: '420909429462',
    projectId: 'tn-thoomai',
    authDomain: 'tn-thoomai.firebaseapp.com',
    storageBucket: 'tn-thoomai.firebasestorage.app',
    measurementId: 'G-17XCX9PKM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5tyRMLv53FfsY1DK68Ap189FsVViAEnU',
    appId: '1:420909429462:android:ffc8dc1a373c38f9f24f77',
    messagingSenderId: '420909429462',
    projectId: 'tn-thoomai',
    storageBucket: 'tn-thoomai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVHALiE5zjPrS6jU03BHNLE_GEU9HNFA4',
    appId: '1:420909429462:ios:8a294dc127f88820f24f77',
    messagingSenderId: '420909429462',
    projectId: 'tn-thoomai',
    storageBucket: 'tn-thoomai.firebasestorage.app',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVHALiE5zjPrS6jU03BHNLE_GEU9HNFA4',
    appId: '1:420909429462:ios:8a294dc127f88820f24f77',
    messagingSenderId: '420909429462',
    projectId: 'tn-thoomai',
    storageBucket: 'tn-thoomai.firebasestorage.app',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXDT12am_VMfR5u0JhRXT4-R9_xHBTCf4',
    appId: '1:420909429462:web:b539921db36daeddf24f77',
    messagingSenderId: '420909429462',
    projectId: 'tn-thoomai',
    authDomain: 'tn-thoomai.firebaseapp.com',
    storageBucket: 'tn-thoomai.firebasestorage.app',
    measurementId: 'G-TB5G0NN7SK',
  );
}
